### ISSUE TITLE
Truthy class value required for addClass to work

### ISSUE THREAD

**Issue by AndrewLeedham** [matteobad/focus-within-polyfill#43]
**Describe the bug**
The `addClass` function will not add a class if the element it is targeting either does not have a class attribute or if it is falsy (e.g. a blank string `""`). Therefore, neither the `js-focus-within` class or `focus-within` classes will be added.

**To Reproduce**
1. Go to https://jsbin.com/fahodibuge/1/edit?html,css,output on IE11
2. Focus the first input (the background doesn't turn red)
3. Focus the second input (the background does turn red)
4. Also if you inspect the page `js-focus-within` is never added to the body.

**Expected behavior**
If either of the inputs were focused in the repro above, I would expect the background to be red. I would also have expected the `js-focus-within` class to be added to the body.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: IE
 - Version: 11

**Comment by AndrewLeedham** [comment]
@matteobad if you can confirm this is a bug/not expected behave, I am happy to put a PR in to fix it. But perhaps this is intended behaviour, so maybe just a doc update?

**Comment by matteobad** [comment]
Hi @AndrewLeedham, yes, unfortunately, I'm aware of this but didn't have the time to fix it. It all started because I was trying to use the `setAttribute` to trigger class name change. Keep in mind that:

- `classList` is not fully supported on older browsers
- In `<svg>` className is an SVGAnimatedString object

Soon I would love to add a little bit of unit test, maybe jest, to avoid this kind of problem in the future. Anyway, I'm very open to PR :)
